{"name": "Проверяем, что без предварительного создания пользователя приходит ошибка, т.к. такого пользователя нет", "status": "passed", "start": 1733668946430, "stop": 1733668946506, "uuid": "8104b00a-4ed1-4c80-b4c7-0f24bca2dab9", "historyId": "e4e1a5d5dd68c2cbdeede2f5a294d6e4", "testCaseId": "e4e1a5d5dd68c2cbdeede2f5a294d6e4", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_nonexistent_user_returns_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-5C5JKNS"}, {"name": "thread", "value": "14412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}