{"name": "Проверяем, что при передаче только пароля приходит ошибка", "status": "passed", "start": 1733668946242, "stop": 1733668946427, "uuid": "9ecabe93-42ef-45e8-8e53-133d7d80dcd3", "historyId": "c4059a3556b8e2110cfacd3396052634", "testCaseId": "c4059a3556b8e2110cfacd3396052634", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_without_login_returns_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-5C5JKNS"}, {"name": "thread", "value": "14412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}